version: "3.7"
services:
  database:
    build:
      context: ./config/database
    container_name: database
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: root
    image: dbi
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./data:/var/lib/mysql
  webserver:
    build:
      context: ./config/webserver
    container_name: webserver
    image: wsi
    ports: 
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./wp-config.php:/var/www/wp-config.php
      - ./html_static:/var/www/html_static

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: wp
      PMA_PASSWORD: pw
    